# http server config
http:
  addr: 'localhost'
  port: 58888
  jwt: "platform"

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  director: './logs'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'CapitalLevelEncoder'
  log-in-console: true

# mysql configuration
mysql:
  addr: '192.168.31.100:3306'
  db-name: 'cluster'
  username: 'root'
  password: '123456'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  log-mode: false
  log-zap: "Error" # Error/Warn/Info/Silent

log:
  # stdout, stderr, file
  format: 'stdout'
  level: 'INFO'
  director-path: '/tmp/logs'

system:
  # 是否开启自动创建表, 生产环境建议设置为 false
  auto-migrate-db: true
