# server configuration
system:
  addr: "192.168.31.100:8080"

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  director: './logs'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'CapitalLevelEncoder'
  log-in-console: true

# mysql configuration
mysql:
  path: '127.0.0.1:3306'
  db-name: 'cluster'
  username: 'root'
  password: '123456'
