# server configuration
system:
  addr: "192.168.31.100:8080"

# zap logger configuration
zap:
  level: 'debug'
  format: 'console'
  director: './logs'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'CapitalLevelEncoder'
  log-in-console: true
